### ISSUE TITLE
sed -i not valid on OSX

### ISSUE THREAD

**Issue by KanedaFr** [AlexanderAgd/SDL2-Android#2]
sed -i command, as used on the script, isn't valid on OSX.

I have no knowledge about sed so I can't help

I tried 
`sed -i'.original' -e "/(call my-dir)/a $MK_ADDON" $DIR/Android.mk`
but it complains about /a not followed by text

**Comment by AlexanderAgd** [comment]
Hello - You need install "gsed" for MAC osx  - I  fixed script.
Can you please confirm problem is fixed ?
Thank you.

**Comment by AlexanderAgd** [comment]
Just  did another fix without -i option, standard "sed"  used. @KanedaFr

**Comment by KanedaFr** [comment]
Thanks, fixed !! 

Do you think you could point to a sample how to use it...?
I found so many way to use SDL2 under android that I'm lost :(

Thanks again! 

Le 21.05.2020 16:49, Alexander a écrit :

> Just did another fix without -i option, standard "sed" used. But not tested on MAC OS. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/AlexanderAgd/SDL2-Android/issues/2#issuecomment-632128660
[2]

**Comment by AlexanderAgd** [comment]
Hello - I plan upload simple sample on github in few days, now working hard on another project.

**Comment by KanedaFr** [comment]
No problem, same here. 

I hope I'll be able to use Tilengine on Android later. 

regards

Le 23.05.2020 16:22, Alexander a écrit :

> Hello - I plan upload simple sample on github in few days, now working hard on another project. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/AlexanderAgd/SDL2-Android/issues/2#issuecomment-633063464
[2]

**Comment by AlexanderAgd** [comment]
Hello :)
You can try build this one 
https://github.com/AlexanderAgd/SDL2-Android-Example
@KanedaFr

**Comment by KanedaFr** [comment]
GREAT!!! It works perfectly on Android Studio , with emulator on MacOSX 

So you have to 

- add your lib on the right folder 

- change path of header folder(s) 

- update LOCAL_SHARED_LIBRARIES and add a new module for each SDL lib if
needed 

perfect! 

Thanks, I'll try with a larger project soon 

Regards 

Le 26.05.2020 00:28, Alexander a écrit :

> Hello :)
> You can try build this one
> https://github.com/AlexanderAgd/SDL2-Android-Example
> @KanedaFr [1] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/KanedaFr
[2]
https://github.com/AlexanderAgd/SDL2-Android/issues/2#issuecomment-633732239
[3]
