### ISSUE TITLE
ERROR: Building SDL2

### ISSUE THREAD

**Issue by paulross80** [AlexanderAgd/SDL2-Android#3]
Hello!
I'm trying to run the script with very few modifications
I'm getting this message:

`Downloaded https://www.libsdl.org/release/SDL2-2.0.14.tar.gz 
Unpack SDL2-2.0.14.tar.gz - done 
make: Entering directory '/home/paul/android/projects/SDL2_bin/SDL2-2.0.14'
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: ./SDL2-2.0.14/Android.mk    
/home/paul/android/sdk/ndk/22.1.7171670/build/core/add-application.mk:88: *** Android NDK: Aborting...    .  Stop.
make: Leaving directory '/home/paul/android/projects/SDL2_bin/SDL2-2.0.14'`

Can you tell me what's wrong?

**Comment by AlexanderAgd** [comment]
Hello I hope u managed already - if not u have to copy here command line you are using
 

 
 

Sent: Friday, July 02, 2021 at 3:30 PM
From: "paulross80" ***@***.***>
To: "AlexanderAgd/SDL2-Android" ***@***.***>
Cc: "Subscribed" ***@***.***>
Subject: [AlexanderAgd/SDL2-Android] ERROR: Building SDL2 (#3)


 

Hello!
I'm trying to run the script with very few modifications
I'm getting this message:

Downloaded https://www.libsdl.org/release/SDL2-2.0.14.tar.gz Unpack SDL2-2.0.14.tar.gz - done make: Entering directory '/home/paul/android/projects/SDL2_bin/SDL2-2.0.14' Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: ./SDL2-2.0.14/Android.mk /home/paul/android/sdk/ndk/22.1.7171670/build/core/add-application.mk:88: *** Android NDK: Aborting... . Stop. make: Leaving directory '/home/paul/android/projects/SDL2_bin/SDL2-2.0.14'

Can you tell me what's wrong?

**Comment by paulross80** [comment]
Yes, closing the issue now, thanks
